name: BSN frontend Pipeline

on:
    push: 
        branches: 
            - ci/pipeline
        paths: 
            - book-network-ui/**
            - docker/frontend/**
            - 'docker-compose.yml'
            - .github/workflows/*-frontend.yml

jobs:
    push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and push Image'
            uses: docker/build-push-action@v5
            with:
              context: book-network-ui
              file: docker/frontend/Dockerfile
              push: true
              tags: ghcr.io/karimdevwm/book-network-ui:latest
            
    deploy:
        needs: push-store-image
        name: deploy image
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
        # check this thread tounderstand why its needed:
        # <https://stackoverflow.com/a/70447517
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"
        - name: cleanup
          run: rm -rf ~/.ssh