name: BSN Backend API Pipeline

on:
    push: 
        branches: 
            - ci/pipeline
        paths: 
            - book-network/**
            - docker/backend/**
            - 'docker-compose.yml'
            - .github/workflows/*-backend.yml

jobs:
    push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and push Image'
            uses: docker/build-push-action@v5
            with:
              context: book-network
              file: docker/backend/Dockerfile
              push: true
              tags: ghcr.io/karimdevwm/book-network-api:latest
      
    deploy:
      name: Deploy Backend
      runs-on: ubuntu-latest
      # needs: [build-image]
      steps:
        - name: Create deployment folder
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ci-cd"
        
        - name: Copy docker-compose file
          run: scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:ci-cd/docker-compose.yml

        - name: Set environment variables and deploy
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            export EMAIL_HOSTNAME=${{ secrets.EMAIL_HOSTNAME }} 
            export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
            export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            cd ci-cd
            docker-compose -f dock-compose.yml pull -q
            docker-compose -f dock-compose.yml up -d
            EOF