name: BSN frontend Pipeline

on:
    push: 
        branches: 
            - ci/pipeline
        paths: 
            - book-network-ui/**
            - docker/frontend/**
            - 'docker-compose.yml'
            - .github/workflows/*-frontend.yml

jobs:
    build-image:
        name: Build Frontend Docker image
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            # - name: extract project version
            #   id: extract_version
            #   run: |
            #     cd book-network-ui
            #     echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
            
            #     - name: Login to GHCR
            #     uses: docker/login-action@v1
            #     with:
            #       username: ${{github.actor}}
            #       password: ${{secrets.GITHUB_TOKEN}}
              
            - name: 'Build Inventory Image'
              uses: docker/build-push-action@v5
              with:
                context: book-network-ui
                file: docker/frontend/Dockerfile
                push: true
                platforms: linux/amd64
                # tags: ${{ github.actor }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }},${{ github.actor }}/bsn-ui:latest
                tags: ghcr.io/inputStr.toLowerCase(${{ github.actor }})/bsn-ui:latest
            
    deploy:
        name: Deploy Frontend
        runs-on: ubuntu-latest
        needs: [build-image]
        steps:
        - name: Create deployment folder
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ci-cd"
        
        - name: Copy docker-compose file
          run: scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:ci-cd/docker-compose.yml

        - name: Set environment variables and deploy
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd ci-cd
            docker-compose -f dock-compose.yml pull -q
            docker-compose -f dock-compose.yml up -d
            EOF